name: kickin_network
description: "Kickin network provides utilities to handle network efficiently and reliably"
version: 0.0.31
homepage: https://github.com/okikday/kickin_network
repository: https://github.com/okikday/kickin_network

environment:
  sdk: ^3.9.5
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.10.0
  internet_connection_checker_plus: ^3.1.0
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
